Changes to hooks to reduce time taken

diff --git a/githooks/post-commit b/githooks/post-commit
--- a/githooks/post-commit
+++ b/githooks/post-commit
@@ -10,7 +10,6 @@ if heroku auth:whoami > /dev/null 2>&1; then
     echo "Logged in to Heroku, proceeding with git update."
     # Check if working directory is clean
     git fetch heroku main || { echo "Failed to fetch latest changes."; exit 1; }
-    git pull heroku main || { echo "Failed to pull latest changes."; exit 1; }
 
     git add .
     git commit -m "Auto-sync from Repo A commit: $commit_msg"
@@ -18,22 +17,12 @@ if heroku auth:whoami > /dev/null 2>&1; then
 
     echo "Commit $commit_msg pushed to heroku/main."
 
-    echo "Updating from seed..."
-    bundle install
-    rails db:create
-    rails db:migrate
-    rails db:seed
-
-    echo "Proceeding with database update."
-    # Try pushing the database
-    if ! heroku pg:push tea_tracker_development DATABASE_URL --app tea-tracker; then
-        echo "Failed to push data to Heroku. Resetting the database and retrying."
-        heroku pg:reset --confirm tea-tracker
-        heroku pg:push tea_tracker_development DATABASE_URL --app tea-tracker
-        echo "Data pushed successfully after reset."
-    else
-        echo "Data pushed successfully to Heroku."
-    fi
+    echo "Resetting heroku database"
+    heroku pg:reset --confirm tea-tracker
+    echo "Running migrations..."
+    heroku run rails db:migrate
+    echo "Seeding database..."
+    heroku run rails db:seed || {echo "Failed to seed database. Rerun commands, as databases are empty."; exit 1;}
 
 else
     echo "Not logged in to Heroku, skipping database update."
